#!/usr/bin/env python3
"""Parse Python source files and output AST as a Python dict module."""

import argparse
import ast
import base64
import pprint
import sys
from pathlib import Path


def ast_to_dict(node: ast.AST, include_locations: bool = True) -> dict:
    """Convert an AST node to a dictionary representation."""
    result = {"_type": node.__class__.__name__}
    for field, value in ast.iter_fields(node):
        result[field] = convert_value(value, include_locations)
    if include_locations:
        for attr in ("lineno", "col_offset", "end_lineno", "end_col_offset"):
            if hasattr(node, attr):
                result[attr] = getattr(node, attr)
    return result


def convert_value(value, include_locations: bool = True):
    """Convert a value from an AST field to its dict representation."""
    if value is None or isinstance(value, (bool, int, float, str)):
        return value
    if isinstance(value, bytes):
        return {"_bytes": base64.b64encode(value).decode("ascii")}
    if isinstance(value, complex):
        return {"_complex": [value.real, value.imag]}
    if value is ...:
        return {"_ellipsis": True}
    if isinstance(value, list):
        return [convert_value(item, include_locations) for item in value]
    if isinstance(value, ast.AST):
        return ast_to_dict(value, include_locations)
    raise TypeError(f"Unexpected AST value type: {type(value).__name__}")


def parse_file(path: Path, include_locations: bool = True) -> dict:
    """Parse a Python file and return its AST as a dict."""
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(path))
    return ast_to_dict(tree, include_locations)


def collect_files(paths: list[Path]) -> list[Path]:
    """Collect all .py files from the given paths."""
    files = []
    for path in paths:
        if path.is_file():
            if path.suffix == ".py":
                files.append(path)
        elif path.is_dir():
            files.extend(sorted(path.rglob("*.py")))
    return files


def main():
    parser = argparse.ArgumentParser(description="Parse Python source to AST dict module")
    parser.add_argument("paths", nargs="+", type=Path, help="Files or directories to parse")
    parser.add_argument("-o", "--output", type=Path, required=True, help="Output module path")
    parser.add_argument("--pretty", action="store_true", help="Indent output for debugging")
    parser.add_argument("--no-locations", action="store_true", help="Omit line/col info")
    args = parser.parse_args()
    files = collect_files(args.paths)
    if not files:
        print("No .py files found", file=sys.stderr)
        sys.exit(1)
    include_locations = not args.no_locations
    modules = {}
    for path in files:
        try:
            modules[str(path)] = parse_file(path, include_locations)
        except SyntaxError as e:
            print(f"Syntax error in {path}: {e}", file=sys.stderr)
            sys.exit(1)
    data = {
        "_py_version": list(sys.version_info[:3]),
        "_py_impl": sys.implementation.name,
        "_py_build": sys.version,
        "modules": modules,
    }
    if args.pretty:
        formatted = pprint.pformat(data, width=120, sort_dicts=False)
    else:
        formatted = repr(data)
    output = f"# Generated by bootstrap.py\nAST = {formatted}\n"
    args.output.write_text(output, encoding="utf-8")
    print(f"Wrote {len(modules)} module(s) to {args.output}")


if __name__ == "__main__":
    main()
